config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :welcome
  resources :stylists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stylist.rb
class Stylist < ApplicationRecord
  # validates :name, presence: true, length: { maximum: 50, minimum: 3 }
  # validates :y_o_e, presence: true, numercality: { greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stylists_controller.rb
class StylistsController < ApplicationController
  
  def index
    @stylists = Stylist.all
  end

  def new
    @stylist = Stylist.new
  end

  def create
    @stylist = Stylist.create(stylist_params)
    redirect_to stylists_path
  end

  private

  def stylist_params
    params.require(:stylist).permit(:name, :stylist_id, :y_o_e)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stylists_helper.rb
module StylistsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalonStatic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md fixed-top-sm justify-content-center flex-nowrap bg-light navbar-light">
      <a class="navbar-brand" href="#">Salon & Co Studios</a>
      <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbar2">
        <span class="navbar-toggler-icon"></span>
      </button>
    </nav>
    <nav class="navbar navbar-expand-md bg-dark navbar-dark">
      <div class="navbar-collapse collapse pt-2 pt-md-0 justify-content-center" id="navbar2">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Home", root_path %>
          </li>
          <li class="nav-item">
            <%= link_to "See our Stylists", stylists_path %>
              <!-- <a class="nav-link" >Meet the Stylists</a> -->
          </li>
          <li class="nav-item">
              <%= link_to "New Stylist", new_stylist_path %>
          </li>
        </ul>
      </div>
    </nav>
<!--     <nav class="navbar sticky-top justify-content-center navbar-expand-lg flex-nowrap navbar-light bg-light">
      <a class="navbar-brand" href="#">Salon & Co Studios</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar2" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </nav>
    <nav class="navbar navbar-dark bg-dark">
      <div class="collapse navbar-collapse pt-2 pt-md-0" id="navbar2">
        <ul class="nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
      </div>
    </nav> -->

    <%= yield %>
  </body>
</html>

app/views/stylists/index.html.erb
<br />

<div class="col-10 offset-1">
  <h1 class="header">Our Stylists</h1>

  <br />

  <% @stylists.each do |stylist| %>
    <div class="card">
      <p>Hi, my name's <%= stylist.name %>!</p>
      <% if stylist.y_o_e.present? %>
        <p>I've been in the salon business for <%= pluralize(stylist.y_o_e, "year") %>.</p>
      <% end %>
    </div>
    <br />
  <% end %>
</div>

app/views/stylists/new.html.erb
<br />

<div class="col-10 offset-1">
  <h1 class="header">Enter a New Stylist's Information</h1>

  <%= simple_form_for @stylist do |f| %>
    <%= f.input :name %>
    <%= f.input :stylist_id, :label => "Stylist ID" %>
    <%= f.input :y_o_e, :label => "Years of Experience" %>
    <%= f.submit "Save" %>
  <% end %>
</div>

app/views/stylists/show.html.erb
<br />

<div>
  <h1>New Stylist</h1>
</div>

app/views/welcome/index.html.erb
<div class="frosty col-10 offset-1">
  <p>We offer four rental studios and one private room to any stylist who is looking for the flexibility and creative freedom that comes with being your own boss.</p>
  <p>We have stylists from all different backgrounds renting from us; <%= link_to "Take a look", stylists_path, class: "link" %> at their profiles to see if their stories resonate with you.</p>
  <p>If you want to choose your own hours, prices, and clientele, please get in touch.</p>
  <p>Can't wait to meet you!</p>
</div>

<div class="info">
  <div class="left col-12 col-sm">
    <h4>Location</h4>
    <p class="x">314 Junction Rd, Madison, WI 53717</p>
  </div>
  <div class="middle col-12 col-sm">
    <h4>Phone Number</h4>
    <p class="x">608 - 123 - 4567</p>
  </div>
  <div class="right col-12 col-sm">
    <h4>Email</h4>
    <p class="x">example.email@email.com</p>
  </div>
</div>